sudo: required
services:
  - docker

before_install:
  - docker build -t afenko/react-tests -f ./client/Dockerfile.dev ./client

script:
  docker run afenko/react-tests npm tests -- --coverage

after_success:
  - docker build -t afenko/multi-client ./client
  - docker build -t afenko/multi-nginx ./nginx
  - docker build -t afenko/multi-server ./server
  - docker build -t afenko/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push afenko/multi-client
  - docker push afenko/multi-nginx
  - docker push afenko/multi-server
  - docker push afenko/multi-worker